const mongoose = require("mongoose");

const segmentSchema = new mongoose.Schema(
  {
    start: Number,
    end: Number,
    type: { type: String, enum: ["highlight", "normal", "dead", "transition", "beat"] },
    score: Number,
    label: String,
  },
  { _id: false }
);

const captionSchema = new mongoose.Schema(
  {
    start: Number,
    end: Number,
    text: String,
    style: { type: String, default: "default" },
  },
  { _id: false }
);

const jobSchema = new mongoose.Schema(
  {
    jobId: { type: String, required: true, unique: true, index: true },
    userId: { type: String, default: "anonymous" },
    status: {
      type: String,
      enum: ["queued", "analyzing", "rendering", "done", "failed"],
      default: "queued",
    },
    progress: { type: Number, default: 0 }, // 0-100
    stage: { type: String, default: "" },   // human-readable current step

    // Input
    inputFile: { type: String, required: true },
    inputMimeType: String,
    durationSeconds: Number,
    fileSizeBytes: Number,

    // Input — multi-video support
    inputFiles: [String], // additional clip filenames (merged before analysis)

    // AI Analysis results
    contentType: {
      type: String,
      enum: ["real_estate", "food", "product", "dance", "travel", "nature", "cinematic",
             "vlog", "interview", "comedy", "fitness", "education", "lifestyle", "unknown"],
      default: "unknown",
    },
    contentTypeConfirmed: { type: Boolean, default: false }, // user confirmed/overrode AI detection
    confidence: Number,
    segments: [segmentSchema],
    captions: [captionSchema],
    beatTimestamps: [Number],
    dominantColors: [String],
    sceneCount: Number,
    hookTextOptions: [String], // 3 AI-generated hook options for user to pick from
    captionsAutoGenerated: { type: Boolean, default: false }, // true when no speech — captions are AI-invented

    // Editing config (user can override)
    template: { type: String, default: "auto" },
    musicFile: String,
    musicOffset: { type: Number, default: 0 },
    aspectRatio: { type: String, default: "9:16" },
    captionStyle: { type: String, default: "modern" },
    transitionStyle: { type: String, default: "fade" },
    transitionDuration: { type: Number, default: 0.3 },
    targetDurationSec: { type: Number, default: 30 },
    includeHookText: { type: Boolean, default: true },
    hookText: String,
    ctaText: String,          // end-screen CTA e.g. "Follow for more 🔥"
    ctaEnabled: { type: Boolean, default: true },
    speedRamp: { type: Boolean, default: false }, // slow-mo on highlights
    zoomPunch: { type: Boolean, default: true },  // subtle zoom punch on beat drops
    exportPreset: { type: String, default: "reels" }, // reels | tiktok | shorts
    editMode: {
      type: String,
      enum: ["auto", "short_reel", "long_reel", "cinematic", "vlog", "travel",
             "wedding", "fast_beat", "food", "business", "emotional"],
      default: "auto",
    },

    // User branding
    muteAudio: { type: Boolean, default: false },
    logoFile: String,
    logoPosition: { type: String, default: "bottom_right" }, // top_left | top_right | bottom_left | bottom_right

    // Output — filenames (on HF Space disk)
    outputFile: String,
    watermarkedFile: String,
    thumbnailFile: String,
    outputResolution: { type: String, default: "1080x1920" },

    // Output — full public URLs served by HF Space
    outputUrl: String,
    watermarkedUrl: String,
    thumbnailUrl: String,

    // Payment
    paid: { type: Boolean, default: false },
    paymentOrderId: String,
    paymentId: String,

    // Error
    error: String,
    celeryTaskId: String,
  },
  { timestamps: true }
);

jobSchema.index({ userId: 1, createdAt: -1 });
jobSchema.index({ status: 1 });

module.exports = mongoose.model("Job", jobSchema);
