export interface Caption {
  start: number;
  end: number;
  text: string;
  style: string;
}

export interface Segment {
  start: number;
  end: number;
  score: number;
  type: "highlight" | "dead" | "normal" | "transition" | "beat";
  label: string;
}

export type ContentType =
  | "real_estate" | "food" | "product" | "dance" | "travel" | "nature" | "cinematic"
  | "vlog" | "interview" | "comedy" | "fitness" | "education" | "lifestyle" | "unknown";

export type TransitionStyle =
  | "fade" | "wipeleft" | "wiperight" | "slideleft" | "slideright"
  | "circleopen" | "dissolve" | "radial" | "zoomin" | "none" | "auto";

export type ExportPreset = "reels" | "tiktok" | "shorts";

export type EditMode =
  | "auto" | "short_reel" | "long_reel" | "cinematic"
  | "vlog" | "travel" | "wedding" | "fast_beat" | "food" | "business" | "emotional";

export interface Job {
  _id: string;
  jobId: string;
  userId: string;
  status: "queued" | "analyzing" | "rendering" | "done" | "failed";
  progress: number;
  stage: string;

  // Input
  inputFile: string;
  inputFiles?: string[];           // extra clips for multi-upload
  durationSeconds?: number;
  fileSizeBytes?: number;

  // Analysis
  contentType: ContentType;
  contentTypeConfirmed?: boolean;
  confidence?: number;
  segments?: Segment[];
  captions?: Caption[];
  beatTimestamps?: number[];
  dominantColors?: string[];
  sceneCount?: number;
  hookTextOptions?: string[];          // 3 AI-generated options for user to pick from
  captionsAutoGenerated?: boolean;     // true when no speech — overlays are AI-invented

  // Edit config
  template: string;
  musicFile?: string;
  aspectRatio: string;
  captionStyle: string;
  transitionStyle: TransitionStyle;
  transitionDuration?: number;
  targetDurationSec: number;
  hookText?: string;
  includeHookText: boolean;
  ctaText?: string;
  ctaEnabled?: boolean;

  // Effects
  speedRamp?: boolean;
  zoomPunch?: boolean;
  exportPreset?: ExportPreset;
  editMode?: EditMode;

  // Output — filenames (on HF Space)
  outputFile?: string;
  watermarkedFile?: string;
  thumbnailFile?: string;

  // Output — full public URLs (served directly by HF Space)
  outputUrl?: string;
  watermarkedUrl?: string;
  thumbnailUrl?: string;

  // Branding
  muteAudio?: boolean;
  logoFile?: string;
  logoPosition?: "top_left" | "top_right" | "bottom_left" | "bottom_right";

  // Payment
  paid: boolean;
  paymentOrderId?: string;
  paymentId?: string;

  error?: string;
  createdAt: string;
  updatedAt: string;
}
